/*
A linguagem fonte é simples, sendo formada por somente dois comandos:
1. Comando de atribuição onde variáveis recebem expressões contendo valores representados por números romanos de 1 a 39;
2. Comando de exibição de variável.
Detalhes:
i. os números são sempre escritos em romanos e em letras maiúsculas.
ii. as variáveis, que não precisam de ser declaradas, são formadas por letra(s) minúscula(s).
iii. o caractere de finalização de comando é o ponto-e-vírgula.
iv.  comentários não são aceitos.
v.  o comando de exibição só aceita uma variável e apresenta o valor em arábicos.
*/


/*  CompiladorExemplo.jj  -  Analisador Semântico */
options {
  DEBUG_PARSER = false;
  DEBUG_TOKEN_MANAGER = false;
}

PARSER_BEGIN(IntermediareTotalCompiler)
import java.io.*;
import java.util.LinkedList;

import Render.AbstractRenderElement;
import Render.BlockElement;
import Render.RenderElementInterface;
import Render.Commands.Output;
import Render.Commands.VariableAttribution;
import Render.Expressions.AbstractExpression;
import Render.Expressions.Goto;
import Render.Expressions.Label;
import Render.Expressions.LogicalOperator;
import Render.Expressions.MathOperator;
import Render.Expressions.StringMathOperator;
import Render.Expressions.Value;
import Render.Expressions.Variable;
import Render.FlowControllers.ConditionalElement;
import Render.FlowControllers.DoWhileElement;
import Render.FlowControllers.ForElement;
import Render.FlowControllers.InlineConditionalElement;
import Render.FlowControllers.LoopElement;

public class IntermediareTotalCompiler {
  static ReferenceTable referenceTable = new ReferenceTable();
  static BlockElement mainBlock; 
  static int totalInlineConditionals = 0;
  public static void main(String args[])  throws ParseException  {
    try {      
      IntermediareTotalCompiler analisador = new IntermediareTotalCompiler (System.in);
      mainBlock = analisador.parse(); 
      String result = mainBlock.render();
      ByteCodeFile.write(result);
      
      System.out.println("Compilado...");
    }   
    catch(TokenMgrError e) {
      System.err.println("Lexical Error:\n" + e.getMessage()); 
    }
    catch(ParseException e) {
      System.err.println("Syntactic Error:\n" + e.getMessage());
    }
    catch(Exception e) {
      System.err.println("Semantic error:\n" + e.getMessage()  );  
      e.printStackTrace();
    }
  }  
}
PARSER_END(IntermediareTotalCompiler)
SKIP : { " " | "\t" | "\r" | "\n" }
SPECIAL_TOKEN :
{
  <SINGLE_LINE_COMMENT: "//" (~["\n","\r"])* ("\n"|"\r"|"\r\n")>
  |
  <MULTIPLE_LINE_COMMENT: "/*" (~["*"])* "*" (~["*","/"] (~["*"])* "*" | "*")* "/">
}

TOKEN : {
      < IF: "if"> |
      < TER_IF: "?"> |
      < ELSE: "else"> |
      < WHILE: "while"> |
      < DO : "do" > |
      < FOR: "for"> |
      <AP: "(">   |
      <FP: ")">   |
      <AC: "{">   |
      <FC: "}">   |
      < PRINT: "print" > |
      < BOOLEAN_CALL: "bool"> |
      < LAMBDA_CALL: "lambda"> |
      < BOOLEAN: "true"  | "false" > |
      <STRING: "\"" (~["\""])* "\"" > |
      < IDENT:   (["a"-"z"]|["A"-"Z"])(["a"-"z"]|["A"-"Z"]|["0"-"9"]|["_"])* > |
      < ATRIB:   ":=" >             |
      < INCREMENT:   "+=" | "-=" | "*=" | "/=" >             |
      < AUTOINCREMENT:   "++" | "--" >             |
      < OR:   "||" >             |
      < AND:   "&&" >             |
      < NEG:   "!" >             |
      < LOGICAL_OPERATOR: "=="  | "!=" | ">" | "<" | ">=" | "<="  > |
      < MATH_OPERATOR_GRAU_2:  "+" | "-">              |
      < MATH_OPERATOR_GRAU_1:  "*" | "/">              |
      < PT_VIRG: ";" >              |
     
      < NUMBER:   (["0"-"9"])+("."(["0"-"9"])+)? > 
}

BlockElement parse() : {BlockElement block = null;}
{
   block=parseBlock() <EOF>
   {
    return block;
   }
}
////////////////////////////////////////////////////////////////////////////////
BlockElement parseBlock() : {BlockElement block = new BlockElement(); AbstractRenderElement child = null;}
{
   ( child = parseCommand() 
   {
      block.addChild(child);
   }
   )*
   {
    return block;
   }
}
////////////////////////////////////////////////////////////////////////////////
AbstractRenderElement parseCommand() : {AbstractRenderElement renderElement=null;}
{
      (
      
      renderElement = print() <PT_VIRG>
      | 
      renderElement = atribui() <PT_VIRG>
      |
      renderElement = logicalIF()
      |
      renderElement = loopWHILE()
      |
      renderElement = loopFOR()
      |
      renderElement = loopDOWHILE()  <PT_VIRG>
      )
     {
      return  renderElement;
     } 
}

////////////////////////////////////////////////////////////////////////////////////
AbstractRenderElement print() : {Output outputElement=null;LinkedList <AbstractExpression> expList; AbstractExpression exp;}
{
      <PRINT> <AP> expList = expression() <FP>
      {
        exp = expList.getLast();
      outputElement = new Output(exp.getTypeIndex());
      outputElement.addAllExpChildren(expList);
      return outputElement;
      }
}
////////////////////////////////////////////////////////////////////////////////////
AbstractRenderElement atribui() : {Token t, attrType; LinkedList <AbstractExpression> expList = null; VariableAttribution var = null; Variable consultVar = null;Value increment; AbstractRenderElement logical=null;}
{
      t=<IDENT>  ((attrType=<ATRIB> (LOOKAHEAD(logicalINLINE(t.image)) expList = logicalINLINE(t.image) | expList = expression()))  | (attrType=<INCREMENT> expList = expression()) | (attrType=<AUTOINCREMENT>))
      {
        if (logical != null) return logical;
        if (referenceTable.exists(t.image)) {
          var = new VariableAttribution("double", t.image, referenceTable.getVariableSerialID(t.image));

          switch (attrType.image) {
            case "+=":
            case "-=":
            case "*=":
            case "/=":
              consultVar = new Variable("double", referenceTable.getVariableSerialID(t.image));
              expList.addFirst(consultVar);
              expList.add(new MathOperator(attrType.image.substring(0,1), consultVar, expList.getLast()));
              break;
            case "++":
            case "--":
              expList = new LinkedList<AbstractExpression>();
              consultVar = new Variable("double", referenceTable.getVariableSerialID(t.image));
              increment = new Value("double", "1");
              expList.add(consultVar);
              expList.add(increment);
              expList.add(new MathOperator(attrType.image.substring(0,1), consultVar, increment));
            break;
            default:
            break;
          }
          var.addAllExpChildren(expList);
        } else if(attrType.image.equals(":=")) {
          var = new VariableAttribution(expList.getLast().getType(), t.image);
          referenceTable.addVariable(var);
          var.addAllExpChildren(expList);
        } else {
          System.out.println("[ ERROR ] Variável " + t.image + " inexistente para incremento.");
          System.exit(-1);
        }
        
        return var;
      }
}

////////////////////////////////////////////////////////////////////////////////////
LinkedList<AbstractExpression> logicalINLINE(String varRef) : {Token t=null; LinkedList <AbstractExpression> exp=null, mainExp =null, elseExp = null;InlineConditionalElement  conditional = null;VariableAttribution var;BlockElement mainBlock = null, elseBlock = null;String mainType= "", elseType="", type = "";}
{
      exp=logicalExpressionOR( ""+(BlockElement.getQtyBlockInstances() + 1), false) (<TER_IF> mainExp = expression() ":" elseExp = expression())
      {

        if(mainExp.isEmpty() || elseExp.isEmpty()) {
          System.out.println("[ERROR] Expressão ternária não pode ter retorno vazio.");
          System.exit(1);
        } 

        mainType = mainExp.getLast().getType();
        elseType = elseExp.getLast().getType();

        if (referenceTable.exists(varRef)) {
          type = referenceTable.getType(varRef);
        } else {
          type = mainType;
        }

        
        mainBlock = new BlockElement();
        elseBlock = new BlockElement();
        mainBlock.addAllExpChildren(mainExp);
        elseBlock.addAllExpChildren(elseExp);   
        
        conditional = new InlineConditionalElement(type, exp, mainType, mainBlock, elseType, elseBlock);
        exp = new LinkedList<AbstractExpression>();
        exp.add(conditional);
        return exp;
      }
}
////////////////////////////////////////////////////////////////////////////////////
AbstractRenderElement loopWHILE() : {Token t; LinkedList <AbstractExpression> expList;LoopElement  loop = null;VariableAttribution var; BlockElement mainBlock =null;}
{
      <WHILE> <AP> expList = logicalExpressionOR(""+(BlockElement.getQtyBlockInstances() + 1), true) <FP> <AC> mainBlock = parseBlock() <FC> 
      {
        loop = new LoopElement(expList, mainBlock);

        return loop;
      }
}
////////////////////////////////////////////////////////////////////////////////////
AbstractRenderElement loopDOWHILE() : {Token t; LinkedList <AbstractExpression> expList;DoWhileElement loop = null;VariableAttribution var; BlockElement mainBlock =null;}
{
      <DO> <AC> mainBlock = parseBlock() <FC> <WHILE> <AP> expList = logicalExpressionOR(""+(BlockElement.getQtyBlockInstances()), true) <FP>
      {
        loop = new DoWhileElement(expList, mainBlock);

        return loop;
      }
}
LinkedList<RenderElementInterface> readAttributionCollection() : {LinkedList<RenderElementInterface> collection = new LinkedList<RenderElementInterface>(); AbstractRenderElement renderElement=null;} {
  ((renderElement = atribui()) {
    collection.add(renderElement);

  })?
  {
    return collection;
  }
}
////////////////////////////////////////////////////////////////////////////////////
AbstractRenderElement loopFOR() : {Token t; LinkedList <AbstractExpression> expList;LoopElement  loop = null;VariableAttribution var; BlockElement mainBlock =null;LinkedList<RenderElementInterface> pre, post;}
{
      <FOR> <AP> pre=readAttributionCollection() <PT_VIRG> expList = logicalExpressionOR(""+(BlockElement.getQtyBlockInstances() + 1), true) <PT_VIRG> post=readAttributionCollection() <FP> <AC> mainBlock = parseBlock() <FC> 
      {
        loop = new ForElement(pre, post, expList, mainBlock);
        return loop;
      }
}
////////////////////////////////////////////////////////////////////////////////////
AbstractRenderElement logicalIF() : {Token t; LinkedList <AbstractExpression> expList;ConditionalElement  conditional = null;VariableAttribution var; BlockElement mainBlock =null, elseBlock = null;}
{
      <IF> <AP> expList = logicalExpressionOR(""+(BlockElement.getQtyBlockInstances() + 1), false) <FP> <AC> mainBlock = parseBlock() <FC> (<ELSE><AC> elseBlock = parseBlock() <FC>)? 
      {
        if (elseBlock != null) {
          conditional = new ConditionalElement(expList, mainBlock, elseBlock);
        } else {
          conditional = new ConditionalElement(expList, mainBlock);
        }
        return conditional;
      }
}
//////////////////////////////////////////////////////////////////////////////////////
LinkedList <AbstractExpression> logicalExpressionOR(String blockTarget, boolean internal) : { Token operacao=null; LinkedList <AbstractExpression> expList; }
{
      expList=logicalExpressionORContent(blockTarget, internal)
      {
       expList.add(new Goto("BlockEnd"+blockTarget));
       if (internal) expList.add(new Label("ORBranch"+blockTarget+"Pass"));

        return expList;
       }
}
//////////////////////////////////////////////////////////////////////////////////////
LinkedList <AbstractExpression> logicalExpressionORInline() : { Token operacao=null; LinkedList <AbstractExpression> expList; String blockTarget = "Inline"+(++totalInlineConditionals); }
{
      expList=logicalExpressionORContent(blockTarget, true)
      {
       expList.add(new Value("int", "0"));
       expList.add(new Goto("ORBranch"+blockTarget+"End"));

       expList.add(new Label("ORBranch"+blockTarget+"Pass"));
       expList.add(new Value("int", "1"));
       expList.add(new Label("ORBranch"+blockTarget+"End"));

        return expList;
       }
}
//////////////////////////////////////////////////////////////////////////////////////
LinkedList <AbstractExpression> logicalExpressionORContent(String blockTarget, boolean internal) : { LinkedList <AbstractExpression> item=null;MathOperator mathOperator = null;Token operacao=null; LinkedList <AbstractExpression> expList = new LinkedList <AbstractExpression> (); int qtyORs = 1; }
{
      item= logicalExpressionAND("ORBranch"+blockTarget+""+qtyORs, internal? "ORBranch"+blockTarget+"Pass" : "BlockBegin"+blockTarget)
      {
       expList.addAll(item);
       }
       ((operacao=<OR>)  item = logicalExpressionAND("ORBranch"+blockTarget+""+(qtyORs + 1), internal? "ORBranch"+blockTarget+"Pass" : "BlockBegin"+blockTarget) 
       {
        expList.add(new Label("ORBranch"+blockTarget+""+qtyORs));
        expList.addAll(item); 

        qtyORs++;
       }

      )* 
      {
       expList.add(new Label("ORBranch"+blockTarget+""+qtyORs));
        return expList;
       }
}
//////////////////////////////////////////////////////////////////////////////////////
LinkedList <AbstractExpression> logicalExpressionAND(String exitTarget, String blockTarget) : { LinkedList <AbstractExpression> item=null,item2=null;MathOperator mathOperator = null;Token operacao=null; LinkedList <AbstractExpression> expList = new LinkedList <AbstractExpression> (); }
{
      item= logicalFactor(blockTarget, false)
      {
        
        expList.addAll(item);
      }
       ((operacao=<AND>)  item = logicalFactor(exitTarget, true) 
       {
       expList.addAll(0,item); 
       

       }

      )* 
      {
       return expList;
       }
}
//////////////////////////////////////////////////////////////////////////////////////
LinkedList <AbstractExpression> logicalFactor(String blockTarget, boolean invert) : { LinkedList <AbstractExpression> item=null, item2=null;LogicalOperator logicalOperator = null;Token operacao=null; LinkedList <AbstractExpression> expList = new LinkedList <AbstractExpression> (); Token neg=null;boolean isInverting;String operation;}
{
      (neg=<NEG>)? item= expression() (operacao=<LOGICAL_OPERATOR> item2=expression())?
      {
       expList.addAll(item);

       isInverting = neg != null ? !invert : invert;
       
       if (operacao == null) {
          expList.add(new Value(item.getLast().getType()));
          operation = ">";
       } else {
         expList.addAll(item2); 
         operation = operacao.image;
       }
      
       logicalOperator = new LogicalOperator(isInverting? LogicalOperator.getInvertedOperator(operation) : operation, item.getLast(), expList.getLast(), blockTarget);
       expList.add(logicalOperator); 
       
       return expList;
       }
}
//////////////////////////////////////////////////////////////////////////////////////
LinkedList <AbstractExpression> expression() : { LinkedList <AbstractExpression> item=null;MathOperator mathOperator = null;Token operacao=null; LinkedList <AbstractExpression> expList = new LinkedList <AbstractExpression> (), acumulator = new LinkedList <AbstractExpression> (); StringMathOperator stringConcat = null; int cumulated = 0;}
{
      (item=factorString() | item= expressionLevel1())
      {
        if(item.getLast().getType().equals("string")) {
          stringConcat = new StringMathOperator("+");
          stringConcat.addChild(item);
        }
       expList.addAll(item);
       }
       ((operacao=<MATH_OPERATOR_GRAU_2>) (item=factorString() | item = expressionLevel1())
       {
        if (stringConcat != null) {
          if (item.getLast().getType().equals("string") && operacao.image.equals("+")) {
           
            if (!acumulator.isEmpty()) {
              stringConcat.addChild(acumulator);
              acumulator = new LinkedList <AbstractExpression> ();
              cumulated = 0;
            }
            stringConcat.addChild(item);
          } else if(operacao.image.equals("+")|| cumulated > 0) {
            acumulator.addAll(item);
            cumulated++;
            if (cumulated > 1) {
              mathOperator = new MathOperator(operacao.image, acumulator.get(acumulator.size() - 2), acumulator.getLast());
              acumulator.add(mathOperator); 
            }
          } else {
            System.out.println("[ ERROR ] Operador inválido para concatenação de strings.\r\nTipo desconhecido: " + operacao.image + "\r\n");
            System.exit(1);
          }
        } else {
          if (item.getLast().getType().equals("string")) {
            stringConcat = new StringMathOperator(operacao.image);
            stringConcat.addChild(expList);
            expList = new LinkedList<AbstractExpression>();
            stringConcat.addChild(item);
          } else {
            expList.addAll(item); 
            mathOperator = new MathOperator(operacao.image, expList.get(expList.size() - 2), expList.getLast());
            expList.add(mathOperator); 
          }
        }
       

       }

      )* 
      {
        if (stringConcat != null) {
          expList.clear();
          stringConcat.addChild(acumulator);
          expList.add(stringConcat);
        }
       return expList;
       }
}
//////////////////////////////////////////////////////////////////////////////////////
LinkedList <AbstractExpression> expressionLevel2() : { LinkedList <AbstractExpression> item=null;MathOperator mathOperator = null;Token operacao=null; LinkedList <AbstractExpression> expList = new LinkedList <AbstractExpression> (); }
{
      item= expressionLevel1()
      {
       expList.addAll(item);
       }
       ((operacao=<MATH_OPERATOR_GRAU_2>)  item = expressionLevel1() 
       {
       expList.addAll(item); 
       mathOperator = new MathOperator(operacao.image, expList.get(expList.size() - 2), expList.getLast());
       expList.add(mathOperator); 
       

       }

      )* 
      {
       return expList;
       }
}
//////////////////////////////////////////////////////////////////////////////////////
LinkedList <AbstractExpression> expressionLevel1() : { MathOperator mathOperator = null;Token operacao=null; LinkedList <AbstractExpression> expList = new LinkedList <AbstractExpression> (), item=null; }
{
      item= factor()
      {
       expList.addAll(item);
       }
       ((operacao=<MATH_OPERATOR_GRAU_1>)  item = factor() 
       {
       expList.addAll(item); 
       mathOperator = new MathOperator(operacao.image, expList.get(expList.size() - 2), expList.getLast());
       expList.add(mathOperator); 
       

       }

      )* 
      {
       return expList;
       }
}
////////////////////////////////////////////////////////////////////////////////////////
LinkedList<AbstractExpression> factor() : {Token t; Variable var=null;Value value = null; int valorNumero;LinkedList <AbstractExpression> expList;}
{
  <AP> (expList = expressionLevel2()) <FP> {
    return expList;
  }
  |
  t = <IDENT>
  {
      
    var = referenceTable.stackVariable(t.image);
    expList = new LinkedList <AbstractExpression> ();
    expList.add(var);
    return expList;
  }
  |
  t = <NUMBER>
  {
    value = new Value("double", t.image);
    expList = new LinkedList <AbstractExpression> ();
    expList.add(value);
    return expList;
  }
  |
  t = <BOOLEAN>
  {
    value = new Value("double", t.image.equals("true")? "1" : "0");
    expList = new LinkedList <AbstractExpression> ();
    expList.add(value);
    return expList;
  }
  |  
  t=<BOOLEAN_CALL><AP> expList=logicalExpressionORInline() <FP>
  {
    return expList;
  }
  |
  <LAMBDA_CALL><AP> expList = logicalINLINE("")<FP>
  {
    return expList;
  }
}
////////////////////////////////////////////////////////////////////////////////////////
LinkedList<AbstractExpression> factorString() : {Token t; Variable var=null;Value value = null; int valorNumero;LinkedList <AbstractExpression> expList;}
{
  t = <STRING>
  {

    value = new Value("string", t.image);
    expList = new LinkedList <AbstractExpression> ();
    expList.add(value);
    return expList;
  }
  
}
//////////////////////////////////////////////////////////////////////////////////////
